### ISSUE TITLE
Realtime metrics proposal

### ISSUE THREAD

**Issue by sublayerio** [armada-alliance/armada-alliance#12]
The idea is to allow every member of the community to expose an endpoint exposing a set of essentials metrics giving the other community members insight on how other SPO's operate.

We'll support the following metrics being exposed:
```
{
   "blockHeight": 123
}
```

**Comment by AstroWa3l** [comment]
Some things to consider adding are:

- Type of Node (relay, BP, router, switch, other)
- Name
- Pool Logo Image (only BP?)
- Temperature
- CPU%
- Memory%
- Block height
- Overclocked (yes/no)
- Overclocked Settings (Speed)
- Failover (yes/no)
- Voltage
- Power
- Current (mA)

**Comment by AstroWa3l** [comment]
this has been included into the new site, so closing this now.
