### ISSUE TITLE
Images on website don't load properly

### ISSUE THREAD

**Issue by AstroWa3l** [armada-alliance/armada-alliance#135]
Seems that some images that are "hardcoded" into the pages like for example on the pool detail pages do not properly load (fetched) from their parent site and thus result in an error. Not sure how to improve this 🤷‍♂️

**Comment by seikoh00** [comment]
Hey my code discovered a bug - cool!  lol

**Comment by sublayerio** [comment]
We could eventually build in some "dead link" detection. For now; which images are you referring to?

**Comment by AstroWa3l** [comment]
The images on our pool website page, I believe we are getting the images from piada.io
