### ISSUE TITLE
 Add compound interest formula for calculator

### ISSUE THREAD

**Issue by AstroWa3l** [armada-alliance/armada-alliance#150]
This is the formula for 1 year:

((stake * ((1 + ((percentage / 100) / 73))) ** (73 * duration)))

**Comment by AstroWa3l** [comment]
@sublayerio I am not sure how to change the calculator for the website. It seems that you should just calculate the "APY" or "Annual percentage yield" and then you can get the rewards breakdown from there.

**Comment by AstroWa3l** [comment]
who cares.

**Comment by sublayerio** [comment]
<img width="905" alt="Screenshot 2021-08-08 at 20 07 23" src="https://user-images.githubusercontent.com/44947294/128641421-c390d937-36f3-40b3-8ec8-63a53bde15c5.png">

This only applies to the first calculator if I'm not mistaken, the total rewards earned should be a compounded amount.

**Comment by sublayerio** [comment]
<img width="937" alt="Screenshot 2021-08-08 at 20 34 03" src="https://user-images.githubusercontent.com/44947294/128642186-56661c1c-54e7-4c9a-800f-d09f8541ed27.png">

Formula works perfectly, had to just drop it in and it worked.
<img width="800" alt="Screenshot 2021-08-08 at 20 34 47" src="https://user-images.githubusercontent.com/44947294/128642205-475fa734-24d5-4321-923f-93218d0944ec.png">
