### ISSUE TITLE
[ASTOR] Rule#3 Every SPO should have a Telegram handle

### ISSUE THREAD

**Issue by tdiesler** [armada-alliance/armada-alliance#194]
I'm stuck with Rule#3 the Telegram handle. IMHO, it is unreasonable to require the use of a specific messenger service that forces me to give my mobile phone number to that service. I also don't understand the Telegram business model, which makes me wonder how they earn their money. If I don't understand that, it is likely that they do in ways that I would not agree with. I'm sorry, Telegram is unfortunately/currently not an option for me.

As I understand, the main point is to be able to speak with other SPOs. There are also other less intrusive ways to that for example the good old mailing list. That delegators can reach the SPO, would IMHO also be a sensible requirement - for that any of Email, Twitter, Discord, Forum and Telegram would work.

Can we perhaps relax Rule#3 a little bit such that Telegram would not be a strict requirement to get the checkmark green?

12,5% of our brothers in ARMs don't have the Rule#3 check mark.

**Comment by AstroWa3l** [comment]
Personally,  it is not a big deal to just want one social media to be used, I do not mind discord or telegram, but the overwhelming majority of direct communication is done on telegram and that is where most of the SPOs (all except one) are. But if more people really want to change the rule we should vote on it. 

While some pools have not passed rule number 3 still not enough for them to care about or mention changing it so I am a little bit torn on whether we should change it or what to do really. I will hope we can get some more feedback from other members. @wcatz @eastpiada
