### ISSUE TITLE
Retired pools are displayed in 'stake-pools' page

### ISSUE THREAD

**Issue by Jack-0** [armada-alliance/armada-alliance#236]
I've noticed a retired pool at "https://armada-alliance.com/stake-pools". Maybe the site should query all <pool-id>'s every X days to ensure all pools are still valid.

**Comment by AstroWa3l** [comment]
Hey thanks for bringing this to our attention, we have to fix the codebase to account for retired pools not sure exactly how @sublayerio wants to handle it.

**Comment by AstroWa3l** [comment]
I wrote a small python script that will check if the pools in our website repo are retired using blockforst API. I have it scheduled up to a cronjob to check once a week but we should integrate it into the website build CI later with Olivier. But for now, this issue is reolved.
