### ISSUE TITLE
Chris_Rain is not spo for MEME pool

### ISSUE THREAD

**Issue by tensafefrogs** [armada-alliance/armada-alliance#66]
Hi, looks like the wrong spo got assigned for MEME pool. Instead could the spo be set to @meme_pool on Twitter?

**Comment by AstroWa3l** [comment]
I would suggest you make a identity file. See the updated readme file for instructions.

**Comment by tensafefrogs** [comment]
Looks like it was just added for me, and the info looks good to me, so thanks!
