### ISSUE TITLE
lastmod for pages are not correct (sitemap.xml)

### ISSUE THREAD

**Issue by sublayerio** [armada-alliance/armada-alliance#79]

**Comment by sublayerio** [comment]
This is now fixed. In the build I had to fetch the git history to properly fetch the lastmod date of each content .md file. @AstroWa3l We have to look into SEO and how the pages are picking up. There's still some room for improvement I believe.

**Comment by AstroWa3l** [comment]
Yes, I will look into SEO improvements this week.
