### ISSUE TITLE
Pool logo not showing correctly

### ISSUE THREAD

**Issue by tdiesler** [armada-alliance/armada-alliance#82]
My daughter has designed this new Logo for ASTOR
http://astorpool.net/img/astor-logo.png

Unfortunately, it shows up as a white circle. Is this perhaps a format/dimension issue?

**Comment by AstroWa3l** [comment]
Hi Tom, I would suggest you head to our assets repo and upload your new image for the logo. https://github.com/armada-alliance/assets

**Comment by sublayerio** [comment]
Great new logo! I've noticed the same thing the last few days when opening the site. I'll take a look at it together with a batch of other things.

**Comment by sublayerio** [comment]
@tdiesler It has to be https in order to be displayed properly.

**Comment by tdiesler** [comment]
... and why would that be? Would it work with a self signed certificate?

**Comment by tdiesler** [comment]
Ok thanks, I'll try to get it all setup.
