### ISSUE TITLE
Why are 3 pools missing from adapools.org

### ISSUE THREAD

**Issue by AstroWa3l** [armada-alliance/armada-alliance#95]
It says we only have 24 members on adapools.org I wonder if we should reach out to them.

**Comment by sublayerio** [comment]
I noticed that too, I think it's caching. Our file is looking good: https://staging.armada-alliance.com/adapools.json Perhaps they should be ordered in some way (old to new or something)

**Comment by AstroWa3l** [comment]
So the problem is this: https://staging.armada-alliance.com/adapools.json is for the "staging" branch, not the main website...So we have not updated the adapools.json in the "main" branch as of yet. Which is the link adapools uses to fetch.

**Comment by sublayerio** [comment]
Good point, although I took care of that. So the current adapools.json (https://armada-alliance.com/adapools.json) is giving the right data. I think it has to do with cache.

**Comment by AstroWa3l** [comment]
Okay, because it seemed like you fixed it, should I send them an email about it (the cache)?

**Comment by sublayerio** [comment]
Sounds like a plan. Did they give you specific instructions of what the file should look like? I find it a bit confusing that the pools are set as keys in an object instead of just being an array. Should the key (numbering) in the object remain the same?

**Comment by AstroWa3l** [comment]
https://github.com/armada-alliance/armada-alliance/blob/main/adapools.json

I believe this is where they are fetching from.

I will let them know this is the new location: https://armada-alliance.com/adapools.json)

**Comment by sublayerio** [comment]
Ah, this totally makes sense then. The old days. Perfect, let's let them know.

**Comment by AstroWa3l** [comment]
However, our logo will still not be displayed since it seems to have moved

https://github.com/armada-alliance/assets/blob/main/ship-420-40kb.png?raw=true

This is a 404

So we need to add in our adapools.json file the new link to the alliance logo which are:

64x64 = https://github.com/armada-alliance/assets/blob/gh-pages/ship-420-40kb.png?raw=true

full size = https://github.com/armada-alliance/assets/blob/gh-pages/ship-420-50kb.png?raw=true

**Comment by sublayerio** [comment]
Fixed: https://armada-alliance.com/adapools.json

**Comment by AstroWa3l** [comment]
This is now working, we had moved our adapools.jon file that adapools.org was using.
