### ISSUE TITLE
Delegation Widget - Errors if no image in extended Metadata

### ISSUE THREAD

**Issue by przcntn** [armada-alliance/armada-alliance#97]
For SPOs wanting to make use of the Nami wallet delegate widget that Armada are hosting they will need to have added an image in the extended metadata else the image variable is 0 and not a string causing error below:
![image](https://user-images.githubusercontent.com/879420/126521763-8b15bc91-4ac7-4653-9cdf-f039f2373448.png)

Using Stales just for example sake (I realise that his works on the actual Armada site but assume thats done differently) 
![image](https://user-images.githubusercontent.com/879420/126522003-49e69fc5-22e4-4691-96a8-04bee6ca7ead.png)

Against one with an image:
![image](https://user-images.githubusercontent.com/879420/126522095-52138f8c-a666-462e-b398-6a6f5977d236.png)

Seems it needs to default to a generic logo from adapools or elsewhere so as to avoid the generic error above.

**Comment by sublayerio** [comment]
@przcntn Great point, thanks for the thorough investigation. I'll let you know once it's resolved :)

**Comment by sublayerio** [comment]
@przcntn Sorry for the long wait, this has been solved as well as the ticker not showing. It's now possible not to have an image defined.

**Comment by sublayerio** [comment]
Still causing problems once delegation is made.

Pool ID under which it happens: `3805681d8d4bc9c7f298c24fdeca3406849e2db84a0708718d96d0b2`

**Comment by sublayerio** [comment]
It's now fixed.
