### ISSUE TITLE
Page Content Improvements

### ISSUE THREAD

**Issue by sublayerio** [armada-alliance/armada-alliance#99]
Part of the displayment of content is still being developed.

The following has to be addressed:
- Spacing amongst content parts (paragraphs, video's, images)
- YouTube video doesn't seem to load properly in some cases (on hard refresh: https://armada-alliance.com/blogs/rpi-resiliency-sbc-otg-blog)
- Page tooltips don't display the page type (stake pool, term, etc) this gives people more context to what they're looking at.
- Page tooltips images should not shrink (flex-shrink-0)
- The overall colors, font weights have to be reconsidered.
<img width="849" alt="Screenshot 2021-07-22 at 09 32 20" src="https://user-images.githubusercontent.com/44947294/126603944-65f420fc-3aef-4b0c-a0e6-ceafc64f8a44.png">
<img width="567" alt="Screenshot 2021-07-22 at 09 33 43" src="https://user-images.githubusercontent.com/44947294/126604094-5c016430-b842-4775-a52f-837363bfafbc.png">

**Comment by AstroWa3l** [comment]
Yeah I noticed the YouTube video wouldn't load as well, I thought it was due to spacing so I padded the YouTube video with extra lines above and below it, but it still didn't work. And yes the colors for text must be adjusted to make it easier to read.
